
services:
  backend:
    container_name: backend
    build: .
    networks:
      - marketplace
    depends_on:
      - pgdb
      - frontend
    volumes:
      - ./target/restfulSpring.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - '8080:8080'

  pgdb:
    container_name: pgdb
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: marketplace
    ports:
      - 5432:5432
    networks:
      - marketplace

  frontend:
    container_name: frontend
    image: grioool/marketplace-frontend:latest
    restart: always
    ports:
      - '9100:80'
    networks:
      - marketplace

networks:
  marketplace:
    driver: bridge

volumes:
  pgdata: